site_name: Test Docs
repo_url: https://github.com/nicholasconnors/docs-test
nav:
  - Home: 'index.md'
  - API: 'api.md'
  - GitHub readme: 'readme.md'
  - copyright.md

copyright: Copyright info goes here

theme:
  name: material

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          show_source: true
          docstring_style: numpy
          annotations_path: brief
- search

markdown_extensions:
  - markdown_include.include:
      base_path: ./