name: Build/Publish Develop Docs 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install pillow cairosvg mike
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "Docs"
          git config --global user.email ""
      - name: Build Docs Website
        run: mike deploy --push dev
