name: Build/Publish Develop Docs 
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  get-version:
    runs-on: ubuntu-latest
    env:
     BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      skip: ${{ steps.get-version.outputs.skip }}
    steps:
      - name: Get branch name
        id: branch_name
        run: |
          branch="${BRANCH_NAME}"
          if [[ "$branch" == "main" || "$branch" == "master" ]]; then
            echo "version=latest" >> $GITHUB_OUTPUT
          elif [[ "$branch" == "dev" ]]; then
            echo "version=dev" >> $GITHUB_OUTPUT
          elif [[ "$branch" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "version=$branch" >> $GITHUB_OUTPUT
          else
            echo "Branch $branch doesn't need docs."
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
  deploy:
    needs: get-version
    if: ${{ !needs.set-version.outputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install pillow cairosvg mike
          pip install mkdocstrings-python
          pip install markdown-include
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "Docs"
          git config --global user.email ""
      - name: Build Docs Website
        run: |
          echo "Deploying site for ${{ needs.get-version.outputs.version }}"
          mike deploy --push ${{ needs.get-version.ouputs.version }}
